-- 학습문제
ALTER TABLE COM_QUESTION
	DROP PRIMARY KEY; -- 학습문제 기본키

-- 학습문제
DROP TABLE IF EXISTS COM_QUESTION RESTRICT;

-- 학습문제
CREATE TABLE COM_QUESTION (
	QST_CODE  NVARCHAR2(30) NOT NULL COMMENT '문제코드', -- 문제코드
	FILE_PATH NVARCHAR2(30) NULL     COMMENT '파일경로' -- 파일경로
);

-- 학습문제
ALTER TABLE COM_QUESTION
	ADD CONSTRAINT PK_COM_QUESTION -- 학습문제 기본키
	PRIMARY KEY (
	QST_CODE -- 문제코드
	);